environment:
  CTAGS_VERSION_MAJOR: 2
  CTAGS_VERSION_MINOR: 1
  CTAGS_BUILD: 59
  CTAGS_VERSION: $(CTAGS_VERSION_MAJOR).$(CTAGS_VERSION_MINOR).0.$(CTAGS_BUILD)
  BUILD_ROOT: '%APPVEYOR_BUILD_FOLDER%\build'
  CTAGS_UTIL_DATE: 2019-03-31
  CTAGS_UTIL_REV: 95975bd1
  CTAGS_UTIL_DIR: util
  matrix:
    - compiler: msbuild
      CONFIGURATION: Release
      ARCH: x86
      CMAKE_GENERATOR: '$(CMAKE_GENERATOR_BASE)'
    - compiler: msbuild
      CONFIGURATION: Release
      ARCH: x64
      CMAKE_GENERATOR: '$(CMAKE_GENERATOR_BASE) Win64'

version: $(CTAGS_VERSION_MAJOR).$(CTAGS_VERSION_MINOR).0.$(CTAGS_BUILD)-{build}

install:
  - git submodule update --init --recursive

build_script:
  - '%APPVEYOR_BUILD_FOLDER%\appveyor\build.bat'

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\appveyor\test.bat'

artifacts:
  - path: ctags-*.zip
