version: 0.0.0.{build}

environment:
  BUILD_ROOT: '%APPVEYOR_BUILD_FOLDER%\build'
  matrix:
    - compiler: msbuild
      CONFIGURATION: Release
      ARCH: x86
      CMAKE_GENERATOR: '$(CMAKE_GENERATOR_BASE)'
    - compiler: msbuild
      CONFIGURATION: Release
      ARCH: x64
      CMAKE_GENERATOR: '$(CMAKE_GENERATOR_BASE) Win64'

build_script:
  - '%APPVEYOR_BUILD_FOLDER%\appveyor\build.bat'

artifacts:
  - path: ctags-*.zip
