name: Pull request workflow
run-name: "PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
on: [pull_request]
env:
  CTAGS_VERSION_MAJOR: 2
  CTAGS_VERSION_MINOR: 1
  CTAGS_BUILD: 99
  CTAGS_UTIL_DIR: util
  PROD_DIR_NAME: prod

jobs:
  GetVersion:
    runs-on: windows-2022
    outputs:
      version: ${{ steps.get.outputs.ver }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - id: get
        run: |
          $outp = & ${{ github.workspace }}\build\version\run.bat
          echo "Version: $outp"
          echo "ver=$outp" >> "$ENV:GITHUB_OUTPUT"
  Windows:
    needs: GetVersion
    runs-on: windows-2022
    defaults:
      run:
        shell: cmd
    env:
      CMAKE_CONFIGURATION: Release
      CMAKE_GENERATOR: "Visual Studio 17 2022"
    strategy:
      fail-fast: true
      matrix:
        ARCH: [x86, x64]
        VERSION: ["${{needs.GetVersion.outputs.version}}"]
        include:
          - ARCH: x86
            CMAKE_ARCHITECTURE: Win32
          - ARCH: x64
            CMAKE_ARCHITECTURE: x64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Build
        run: |
          ${{ github.workspace }}\build\build\run.bat
        env:
          CMAKE_ARCHITECTURE_ARG: -A ${{ matrix.CMAKE_ARCHITECTURE }}
          BUILD_ROOT: ${{ runner.temp }}
          PROD_DIR: ${{ runner.temp }}\${{ env.PROD_DIR_NAME }}

      - name: Test
        run: |
          ${{ github.workspace }}\build\test\run.bat
        env:
          BUILD_ROOT: ${{ runner.temp }}
