name: Pull request
run-name: "PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
on: [pull_request]
env:
  CTAGS_VERSION_BUILD: 0
  CTAGS_UTIL_DIR: util
  PROD_DIR_NAME: prod

jobs:
  Windows:
    runs-on: windows-2022
    env:
      CMAKE_CONFIGURATION: Release
      CMAKE_GENERATOR: "Visual Studio 17 2022"
    defaults:
      run:
        shell: cmd
    strategy:
      matrix:
        ARCH: [x86, x64]
        include:
          - ARCH: x86
            CMAKE_ARCHITECTURE: Win32
          - ARCH: x64
            CMAKE_ARCHITECTURE: x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Build
        run: |
          ${{ github.workspace }}\build\build\run.bat
        env:
          CMAKE_ARCHITECTURE_ARG: -A ${{ matrix.CMAKE_ARCHITECTURE }}
          BUILD_ROOT: ${{ runner.temp }}
          PROD_DIR: ${{ runner.temp }}\${{ env.PROD_DIR_NAME }}

      - name: Test
        run: |
          ${{ github.workspace }}\build\test\run.bat
        env:
          BUILD_ROOT: ${{ runner.temp }}
